package com.revature.revabooks.repos;

import com.revature.revabooks.models.AppUser;
import com.revature.revabooks.models.Role;
import com.revature.revabooks.util.ConnectionFactory;

import java.sql.*;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

public class UserRepository {


//    public UserRepository() {
//        System.out.println("[LOG] - Instantiating " + this.getClass().getName());
//    }

    private String baseQuery = "SELECT * FROM revabooks.app_users au " +
            "JOIN revabooks.user_roles ur " +
            "ON au.role_id = ur.id ";


    public Optional<AppUser> findUserById(int id) {

        Optional<AppUser> _user = Optional.empty();
        try (Connection conn = ConnectionFactory.getConnFactory().getConnection()) {
            String sql = (baseQuery + "WHERE au.id = ?");
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setInt(1, id);

            Set<AppUser> rs = mapResultSet(pstmt.executeQuery());
            if (!rs.isEmpty()) {
                _user = rs.stream().findFirst();
            }


        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }


        return _user;

    }


    public Set<AppUser> findAllUsers() {
        Set<AppUser> users = new HashSet<>();
        try (Connection conn = ConnectionFactory.getConnFactory().getConnection()) {

            String sql = "SELECT * FROM revabooks.app_users au " +
                    "JOIN revabooks.user_roles ur " +
                    "ON au.role_id = ur.id ";
            ;
            Statement stmt = conn.createStatement();
            stmt.executeQuery(sql);

            ResultSet rs = stmt.executeQuery(sql);
            users = mapResultSet(rs);

        } catch (Exception e) {
            e.printStackTrace();
        }

        return users;
    }


    public Optional<AppUser> findUserByCredentials(String username, String password) {


        Optional<AppUser> _user = Optional.empty();

        try (Connection conn = ConnectionFactory.getConnFactory().getConnection()) {
            String sql = "SELECT * FROM revabooks.app_users au JOIN revabooks.user_roles ur ON au.role_id = ur.id WHERE username = ? AND PASSWORD = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, password);

            ResultSet rs = pstmt.executeQuery();

            _user = mapResultSet(rs).stream().findFirst();

        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }

        return _user;
    }

    public Optional<AppUser> findUserByUsername(String username) {

        Optional<AppUser> _user = Optional.empty();

        try (Connection conn = ConnectionFactory.getConnFactory().getConnection()) {

            String sql = "SELECT * FROM revabooks.app_users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);

            ResultSet rs = pstmt.executeQuery();
            _user = mapResultSet(rs).stream().findFirst();


        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }

        return _user;

    }

    public void save(AppUser newUser) {


        try (Connection conn = ConnectionFactory.getConnFactory().getConnection()) {

            String sql = "INSERT INTO revabooks.app_users (username, password, first_name, last_name, email, role_id) " +
                    "VALUES (?, ? , ? , ? , ? , ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql, new String[]{"id"}); //retrieve autogenerated values


            pstmt.setString(1, newUser.getUsername());
            pstmt.setString(2, newUser.getPassword());
            pstmt.setString(3, newUser.getFirstName());
            pstmt.setString(4, newUser.getLastName());
            pstmt.setString(5, newUser.getEmail());
            pstmt.setInt(6, newUser.getRole().ordinal() + 1);

            int rowsInserted = pstmt.executeUpdate();

            if (rowsInserted != 0) {
                ResultSet rs = pstmt.getGeneratedKeys();

                rs.next();
                newUser.setId(rs.getInt(1));

            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }
    }

    private Set<AppUser> mapResultSet(ResultSet rs) throws SQLException {

        Set<AppUser> users = new HashSet<>();


        while (rs.next()) {
            AppUser temp = new AppUser();
            temp.setId(rs.getInt("id"));
            temp.setUsername(rs.getString("username"));
            temp.setPassword(rs.getString("password"));
            temp.setFirstName(rs.getString("first_name"));
            temp.setLastName(rs.getString("last_name"));
//            temp.setRole(Role.getByName(rs.getString("name")));
            users.add(temp);
        }

        return users;

    }


}